---
- hosts: localhost
  pre_tasks:
    - name: Load host variables
      include: host_vars/main.yml
  roles:
    # Package Manager
    - role: apt
      when: roles.apt
    
    # Network
    - role: firmware_iwlwifi
      when: roles.firmware_iwlwifi
    
    - role: network
      when: roles.network
    
    - role: wpa_supplicant
      when: roles.wpa_supplicant
    
    # Display & Window Manager
    - role: xorg
      when: roles.xorg
    
    - role: bash
      when: roles.bash
    
    - role: i3
      when: roles.i3
    
    - role: unclutter
      when: roles.unclutter

    # File System Software
    - role: resilio_sync
      when: roles.resilio_sync
    
    # Identity
    - role: openssh_client
      when: roles.openssh_client
    
    - role: git
      when: roles.git
    
    # Common Applications
    - role: vim
      when: roles.vim
    
    - role: htop
      when: roles.htop
    
    - role: ranger
      when: roles.ranger
    
    - role: scrot
      when: roles.scrot
    
    - role: mupdf
      when: roles.mupdf
    
    - role: keepassx
      when: roles.keepassx
    
    - role: chromium
      when: roles.chromium
    
    # Multimedia
    - role: gimp
      when: roles.gimp
    
    - role: inkscape
      when: roles.inkscape

    - role: cmus
      when: roles.cmus

    # System Administration
    - role: dnsutils
      when: roles.dnsutils

    - role: ansible
      when: roles.ansible

    # Disk Management
    - role: gnome_disk_utility
      when: roles.gnome_disk_utility

    # Developer Tools
    - role: make
      when: roles.make

    # Latex Writing
    - role: texlive
      when: roles.texlive

    # Web Development
    - role: nodejs
      when: roles.nodejs

