---
- hosts: localhost
  pre_tasks:
    - name: Load host variables
      include: host_vars/main.yml
  roles:
    # Package Manager
    - role: apt
      when: roles.apt
    
    # Network
    - role: firmware_iwlwifi
      when: roles.firmware_iwlwifi
    
    - role: network
      when: roles.network
    
    - role: wpa_supplicant
      when: roles.wpa_supplicant
    
    # Display & Window Manager
    - role: xorg
      when: roles.xorg
    
    - role: bash
      when: roles.bash
    
    - role: i3
      when: roles.i3
    
    - role: unclutter
      when: roles.unclutter

    # Theme
    - role: arc_theme
      when: roles.arc_theme

    # File System Software
    - role: resilio_sync
      when: roles.resilio_sync
    
    # Identity
    - role: openssh_client
      when: roles.openssh_client
    
    - role: git
      when: roles.git
    
    # Common Applications
    - role: vim
      when: roles.vim
    
    - role: htop
      when: roles.htop
    
    - role: ranger
      when: roles.ranger
    
    - role: scrot
      when: roles.scrot
    
    - role: alsamixer
      when: roles.alsamixer
    
    - role: neofetch
      when: roles.neofetch

    - role: mupdf
      when: roles.mupdf
    
    - role: keepassx
      when: roles.keepassx
    
    - role: chromium
      when: roles.chromium

    - role: tor
      when: roles.tor
   
    - role: spotify_client
      when: roles.spotify_client
    
    - role: libreoffice
      when: roles.libreoffice

    # Multimedia
    - role: gimp
      when: roles.gimp
    
    - role: inkscape
      when: roles.inkscape

    - role: cmus
      when: roles.cmus

    # System Administration
    - role: dnsutils
      when: roles.dnsutils

    - role: telnet
      when: roles.telnet

    - role: curl
      when: roles.curl

    - role: netcat
      when: roles.netcat

    - role: ansible
      when: roles.ansible

    - role: boto
      when: roles.boto

    - role: awscli
      when: roles.awscli

    - role: gnupg
      when: roles.gnupg

    - role: remmina
      when: roles.remmina

    # Disk Management
    - role: gnome_disk_utility
      when: roles.gnome_disk_utility

    # Developer Tools
    - role: make
      when: roles.make

    # Latex Writing
    - role: texlive
      when: roles.texlive

    # Python Development
    - role: python3
      when: roles.python3

    - role: python3_pip
      when: roles.python3_pip

    - role: virtualenv
      when: roles.virtualenv

    # Web Development
    
    # NodeJS
    - role: nodejs
      when: roles.nodejs

    - role: npm
      when: roles.npm
    
    # Flask Development
    - role: lsyncd
      when: roles.lsyncd

    # Visualization
    - role: plantuml
      when: roles.plantuml

