---
- hosts: localhost
  pre_tasks:
    - name: Gather hostname
      command: hostname
      register: hostname

    - name: Load vm variables
      include_vars:
        file: "host_vars/vm.yml"
      when: hostname.stdout == "vm"

    - name: Load thinkpad variables
      include_vars:
        file: "host_vars/thinkpad.yml"
      when: hostname.stdout == "thinkpad"

  roles:
    # Package Manager
    - apt
    # Network
    - network
    - wpa_supplicant
    # Display & Window Manager
    - xorg
    - bash
    - i3
    # File System Software
    - resilio_sync
    # Identity
    - openssh
    - git
    # Common Applications
    - vim
    - htop
    - ranger
    - scrot
    - mupdf
    - keepassxc
    - firefox
    # Multimedia
    - gimp
    - inkscape

