---
- hosts: localhost
  pre_tasks:
    - name: Load host variables
      include: host_vars/main.yml
  tasks:
    - name: Execute roles
      include_role:
        name: "{{ item }}"
      with_items: "{{ roles }}"

