---
- hosts: localhost
  vars_files:
    - secrets.yml
  tasks:
    - name: Execute roles
      include_role:
        name: "{{ role }}"
      loop_control:
        loop_var: role
      loop:
        - common
        - window_manager
        - file_management
        - web_browser
        - development
        - system_administration
        - multimedia
        - documentation
        - security
        - graphic_design
        - unixporn
        - chat_clients
