# 1) sudo apt-get update && sudo apt-get -y upgrade
# 2) sudo apt-get -y install ansible
# 3) sudo visudo
# + patrick ALL=(ALL) NOPASSWD:ALL

---
- hosts: localhost
  vars:
    username: patrick
    git_name: Patrick Murray
    git_email: patrick@meteoritesoftware.com
  tasks:
      # Install Packages
    - pacman:
        name:  {{ item }}
        state: latest
        update_cache: True
        upgrade: True
      with_items:
        # Window Manager
        - i3-wm

    - git_config:
        scope: global
        name: user.name
        value: {{ git_name }}
      become: True
      become_user: patrick

    - git_config:
        scope: global
        name: user.email
        value: {{ git_email }}
      become: True
      become_user: patrick

