# 1) sudo apt-get update && sudo apt-get -y upgrade
# 2) sudo apt-get -y install ansible
# 3) sudo visudo
# + patrick ALL=(ALL) NOPASSWD:ALL

---
- hosts: localhost
  vars:
    username: patrick
    git_name: Patrick Murray
    git_email: patrick@meteoritesoftware.com
  tasks:
      # Install Packages
    - pacman:
        name:  "{{ item }}"
        state: latest
        update_cache: True
        upgrade: True
      with_items:
        # Window System
        - xorg
        - xorg-xinit
        # Window Manager
        - i3-wm
        # Version Control System
        - git
      become: True

    - git_config:
        scope: global
        name: user.name
        value: "{{ git_name }}"

    - git_config:
        scope: global
        name: user.email
        value: "{{ git_email }}"

