---
- name: Install xorg
  package:
    name: xorg
    state: latest
  become: True

- name: Configure .xinitrc
  copy:
    src: files/.xinitrc
    dest: ~/.xinitrc

- name: Configure .Xresources
  copy:
    src: files/.Xresources
    dest: ~/.Xresources

- name: Install xbacklight
  package:
    name: xbacklight
    state: latest
  become: True

- name: Install xdg-user-dirs
  package:
    name: xdg-user-dirs
    state: latest
  become: True

- name: Create home directory structure
  command: xdg-user-dirs-update

- name: Install xterm
  package:
    name: xterm
    state: latest
  become: True

