---
- name: Install xorg
  package:
    name: xorg
    state: latest
  become: True

- name: Configure .xinitrc
  copy:
    src: files/.xinitrc
    dest: ~/.xinitrc

- name: Configure .Xresources
  copy:
    src: files/.Xresources
    dest: ~/.Xresources

- name: Install xbacklight
  package:
    name: xbacklight
    state: latest
  become: True

- name: Install xdg-user-dirs
  package:
    name: xdg-user-dirs
    state: latest
  become: True

- name: Create home directory structure
  command: xdg-user-dirs-update

- name: Create xdg Configuration Directory
  file:
    path: ~/.local/share/applications
    state: directory
    recurse: True

- name: Configure xdg Default Applications
  copy:
    src: files/defaults.list
    dest: ~/.local/share/applications/defaults.list

- name: Install xterm
  package:
    name: xterm
    state: latest
  become: True

