---
- name: Update APT Source List
  copy:
    src: "files/sources/debian.list"
    dest: "/etc/apt/sources.list"
  register: updated_source
  become: True

- name: Update APT Cache
  apt:
    update_cache: True
  when: updated_source.changed
  become: True

- name: Upgrade APT Distribution
  apt:
    upgrade: True
  when: updated_source.changed
  become: True

