---
- name: Update APT Source List
  copy:
    src: "files/sources/debian.list"
    dest: "/etc/apt/sources.list"
  become: True

- name: Update Local APT Repository Cache
  apt:
    update_cache: True
  become: True

- name: Upgrade APT Distribution Packages
  apt:
    upgrade: dist
  become: True

