---
- name: Update APT Source List
  copy:
    src: "files/sources/debian/testing.list"
    dest: "/etc/apt/sources.list"
  register: updated_source
  become: True

- name: Update APT Cache
  apt:
    update_cache: True
  when: updated_source.changed
  become: True

- name: Upgrade APT Distribution
  apt:
    upgrade: True
  when: updated_source.changed
  become: True

- name: Install apt-transport-https
  package:
    name: apt-transport-https
    state: latest
  become: True

- name: Install unattended-upgrades
  package:
    name: unattended-upgrades
    state: latest
  become: True

