---
- name: Include Components
  include_tasks:
    file: "components/{{ item }}.yml"
  loop:
    - dnf_automatic
    - firewalld
    - gnupg
    - bitwarden
    - sshd
    - passim
#    - yubikey
#    - pam
