---
- name: Add NodeJS APT Repository GPG Key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: True

- name: Add NodeJS APT Repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_9.x stretch main
    update_cache: True
  become: True

- name: Install npm
  package:
    name: npm
    state: latest
  become: True

