---
- name: Restrict Network Interface Configuration
  file:
    path: /etc/network/interfaces
    mode: 0600


- name: Configure Network Interface
  template:
    src: templates/interfaces/interfaces
    dest: /etc/network/interfaces


- name: Configure DHCP Client
  template:
    src: templates/interfaces/dhclient.conf
    dest: /etc/dhcp/dhclient.conf
