---
- name: Install wpasupplicant
  package:
    name: wpasupplicant
    state: latest


- name: Configure WPA Supplicant File
  copy:
    src: files/wpa_supplicant/wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf


- name: Restrict WPA Supplicant File
  file:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    mode: 0600
