---
- name: Install moby-engine
  package:
    name: moby-engine
    state: latest


- name: Install docker-compose
  package:
    name: docker-compose
    state: latest


- name: Create docker group
  group:
    name: docker
    state: present


- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: 
      - docker
    append: True

