---
- name: Install docker.io
  package:
    name: docker.io
    state: latest


- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest


- name: Create docker group
  group:
    name: docker
    state: present


- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: 
      - docker
    append: True

