---
# $ gpg --show-keys gpg 
# pub   rsa4096 2017-02-22 [SCEA]
#      9DC858229FC7DD38854AE2D88D81803C0EBFCD88
# uid                      Docker Release (CE deb) <docker@docker.com>
# sub   rsa4096 2017-02-22 [S]

- name: Download and add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyring: /etc/apt/keyrings/docker.gpg


- name: Determine system architecture
  shell: dpkg --print-architecture
  register: dpkg_arch


- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: "/etc/apt/sources.list.d/docker.list"
    state: present


- name: Install docker-ce
  package:
    name: docker-ce
    state: latest


- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest


- name: Create docker group
  group:
    name: docker
    state: present


- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: 
      - docker
    append: True
