---
- name: Install git
  package:
    name: git
    state: latest


- name: Configure git user name
  git_config:
    name: user.name
    value: Patrick Murray
    scope: global
  become: True
  become_user: "{{ user.name }}"


- name: Configure git user email
  git_config:
    name: user.email
    value: patrickm129@gmail.com
    scope: global
  become: True
  become_user: "{{ user.name }}"
