---
- name: Install podman
  package:
    name: podman
    state: latest


- name: Install podman-compose
  package:
    name: podman-compose
    state: latest


- name: Install podman-docker
  package:
    name: podman-docker
    state: latest


- name: Install podman-desktop
  flatpak:
    name: io.podman_desktop.PodmanDesktop
    remote: flathub
    state: present


- name: Create podman group
  group:
    name: podman
    state: present


- name: Add user to podman group
  user:
    name: "{{ user.name }}"
    groups: 
      - podman
    append: True


- name: Configure podman systemd unit
  systemd:
    name: podman
    state: started
    enabled: True
