---
- name: Add Microsoft package signing key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Visual Studio Code yum repository
  yum_repository:
    name: visual-studio-code
    description: Visual Studio Code YUM Repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: True
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install Visual Studio Code
  package:
    name: code
    state: latest

