---
# $ gpg --show-keys microsoft.asc 
# ...
# pub   rsa2048 2015-10-28 [SC]
#       BC528686B50D79E339D3721CEB3E94ADBE1229CF
# uid                      Microsoft (Release signing) <gpgsecurity@microsoft.com>
- name: Add Microsoft package signing key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    fingerprint: "BC528686B50D79E339D3721CEB3E94ADBE1229CF"

- name: Add Visual Studio Code yum repository
  yum_repository:
    name: visual-studio-code
    description: Visual Studio Code YUM Repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: True
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install Visual Studio Code
  package:
    name: code
    state: latest

