---
# Reference Documentation:
# 1. https://help.gnome.org/system-admin-guide/power-settings.html
# 2. https://developer.gnome.org/gio/stable/GSettings.html


# POWER BUTTON BEHAVIOR


- name: Configure power button behavior
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
    value: "'{{ gnome.power_management.power_button.action }}'"
    state: present
  become_user: "{{ user.name }}"
  become: True


# SHOW BATTERY PERCENTAGE


- name: Show battery percentage in system tray
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "{{ gnome.desktop.panel.battery.show_percentage | lower }}"
    state: present
  become_user: "{{ user.name }}"
  become: True


# AUTOMATIC SUSPEND - AC POWER


- name: Configure gnome AC-power inactivity action
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'{{ gnome.inactivity.ac_power.action }}'"
    state: present
  become_user: "{{ user.name }}"
  become: True


- name: Configure gnome AC-power inactivity timeout
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: "{{ gnome.inactivity.ac_power.timeout | int }}"
    state: present
  become_user: "{{ user.name }}"
  become: True