---
- name: Install wpasupplicant
  apt:
    name: wpasupplicant
    state: latest
  become: True


- name: Restrict Network Interface Configuration
  file:
    path: /etc/network/interfaces
    mode: 0600
  become: True


- name: Configure Networking systemd Unit
  copy:
    src: files/networking.service
    dest: /lib/systemd/system/networking.service
  become: True


- name: Reload systemd Unit
  systemd:
    name: networking.service
    state: restarted
    daemon_reload: True
  become: True


- name: Configure WPA Supplicant File
  copy:
    src: files/wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
  become: True
  register: wpa_supplicant


- name: Restrict WPA Supplicant File
  file:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    mode: 0600
  become: True


- name: Configure Network Interface
  copy:
    src: files/interfaces
    dest: /etc/network/interfaces
  become: True


- name: Configure DHCP Client
  copy:
    src: files/dhclient.conf
    dest: /etc/dhcp/dhclient.conf
  become: True
