---
- name: Restrict Network Interface Configuration
  file:
    path: /etc/network/interfaces
    mode: 0600
  become: True

- name: Configure Network Interface
  template:
    src: templates/interfaces
    dest: /etc/network/interfaces
  become: True

- name: Configure Network systemd Unit
  copy:
    src: files/networking.service
    dest: /lib/systemd/system/networking.service
  become: True
  register: networking_unit

- name: Reload Network systemd Unit
  systemd:
    name: networking.service
    state: restarted
    daemon_reload: True
  become: True
  when: networking_unit.changed

- name: Configure Network Resume systemd Unit
  copy:
    src: files/networking_resume.service
    dest: /lib/systemd/system/networking_resume.service
  become: True
  register: networking_resume_unit

- name: Reload Network Reload systemd Unit
  systemd:
    name: networking_resume.service
    enabled: True
    daemon_reload: True
  become: True
  when: networking_resume_unit.changed

- name: Bring ethernet interface up
  command: "ip link set dev {{ ethernet_interface }} up"
  become: True
  when: ethernet_interface is not None

- name: Bring wireless interface up
  command: "ip link set dev {{ wireless_interface }} up"
  become: True
  when: wireless_interface is not None

- name: Configure DHCP Client
  template:
    src: templates/dhclient.conf
    dest: /etc/dhcp/dhclient.conf
  become: True

