---
- name: Install xorg
  apt:
    name: xorg
    state: latest
  become: True


- name: Configure .xinitrc
  copy:
    src: files/.xinitrc
    dest: ~/.xinitrc


- name: Configure .Xresources
  copy:
    src: files/.Xresources
    dest: ~/.Xresources


- name: Install xdg-user-dirs
  apt:
    name: xdg-user-dirs
    state: latest
  become: True


- name: Create Base Directory Structure
  command: xdg-user-dirs-update


- name: Install i3
  apt:
    name: i3
    state: latest
  become: True


- name: Create .config Directory
  file:
    path: ~/.config
    state: directory


- name: Create .config/i3 Directory
  file:
    path: ~/.config/i3
    state: directory


- name: Configure i3
  copy:
    src: files/i3/config
    dest: ~/.config/i3/config


- name: Create .config/i3status Directory
  file:
    path: ~/.config/i3status
    state: directory


- name: Configure i3status
  copy:
    src: files/i3status/config
    dest: ~/.config/i3status/config


- name: Install xterm
  apt:
    name: xterm
    state: latest
  become: True


- name: Configure .bashrc
  copy:
    src: files/.bashrc
    dest: ~/.bashrc


- name: Configure .bash_profile
  copy:
    src: files/.bash_profile
    dest: ~/.bash_profile


- name: Install vim
  apt:
    name: vim
    state: latest
  become: True


- name: Configure .vimrc
  copy:
    src: files/.vimrc
    dest: ~/.vimrc


- name: Install htop
  apt:
    name: htop
    state: latest
  become: True


- name: Install ranger
  apt:
    name: ranger
    state: latest
  become: True

