---

#- name: Add tor-browser GPG key
#  apt_key:
#    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc


- name: Add Debian experimental repository
  apt_repository:
    repo: deb https://deb.debian.org/debian buster-backports main contrib
    update_cache: True


#- name: Install deb.torproject.org-keyring
#  package:
#    name: deb.torproject.org-keyring
#    state: latest


- name: Install tor
  package:
    name: tor
    state: latest


- name: Install torbrowser-launcher
  apt:
    name: torbrowser-launcher
    default_release: buster-backports
    state: latest
