---
- name: Create ~/.ssh directory
  file:
    path: ~/.ssh
    state: directory
    mode: 0700
  become: True
  become_user: "{{ user.name }}"


- name: Configure SSH
  copy:
    src: files/ssh/config
    dest: ~/.ssh/config
    mode: 0644
  become: True
  become_user: "{{ user.name }}"


- name: Add Workstation 2026-05-02 SSH private key
  copy:
    src: files/ssh/id-ed25519-workstation-2026-05-02
    dest: ~/.ssh/id-ed25519-workstation-2026-05-02
    mode: 0600
  become: True
  become_user: "{{ user.name }}"


- name: Add Workstation 2026-05-02 SSH public key
  copy:
    src: files/ssh/id-ed25519-workstation-2026-05-02.pub
    dest: ~/.ssh/id-ed25519-workstation-2026-05-02.pub
    mode: 0644
  become: True
  become_user: "{{ user.name }}"


- name: Add Zbook 2017-09-27 SSH public key
  copy:
    src: files/ssh/id-rsa-zbook-2017-09-27.pub
    dest: ~/.ssh/id-rsa-zbook-2017-09-27.pub
    mode: 0644
  become: True
  become_user: "{{ user.name }}"


- name: Add Zbook 2017-09-27 SSH private key
  copy:
    src: files/ssh/id-rsa-zbook-2017-09-27
    dest: ~/.ssh/id-rsa-zbook-2017-09-27
    mode: 0600
  become: True
  become_user: "{{ user.name }}"