---
# $ gpg --show-keys gpg
# pub   rsa4096 2026-09-09 [SC] [expires: 2031-09-08]
#       D55C0D1AC78A8D8126CB631CFC9CA96ACA026560
# uid                      HashiCorp Security (HashiCorp Package Signing) <security+packaging@hashicorp.com>
- name: Add HashiCorp package signing key
  rpm_key:
    key: https://rpm.releases.hashicorp.com/gpg
    fingerprint: "D55C0D1AC78A8D8126CB631CFC9CA96ACA026560"

- name: Add HashiCorp yum repository
  yum_repository:
    name: hashicorp
    description: HashiCorp YUM Repository
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgcheck: True
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    includepkgs: terraform

- name: Install Terraform
  package:
    name: terraform
    state: latest
