---
- name: Install keepassxc
  package:
    name: keepassxc
    state: latest


- name: Copy database to home folder
  copy:
    src: "files/keepassx/passwords.kdbx"
    dest: "{{ user.home }}"
  become: True
  become_user: "{{ user.name }}"
