---
- name: Install i3
  package:
    name: i3
    state: latest


- name: Create .config Directory
  file:
    path: ~/.config
    state: directory
  become: True
  become_user: "{{ user.name }}"


- name: Create .config/i3 Directory
  file:
    path: ~/.config/i3
    state: directory
  become: True
  become_user: "{{ user.name }}"


- name: Configure i3
  copy:
    src: files/i3wm/i3/config
    dest: ~/.config/i3/config
  become: True
  become_user: "{{ user.name }}"


- name: Create .config/i3status Directory
  file:
    path: ~/.config/i3status
    state: directory
  become: True
  become_user: "{{ user.name }}"


- name: Configure i3status
  copy:
    src: files/i3wm/i3status/config
    dest: ~/.config/i3status/config
  become: True
  become_user: "{{ user.name }}"
