---
- name: Install rofi
  package:
    name: rofi
    state: latest
  become: True

- name: Create rofi configuration directory
  file:
    state: directory
    path: ~/.config/rofi

- name: Configure rofi
  copy:
    src: files/rofi/config
    dest: ~/.config/rofi/config
