---
- name: Install xorg-server
  package:
    name: xorg-server
    state: latest


- name: Install xorg-xinit
  package:
    name: xorg-xinit
    state: latest


- name: Install xorg-xrandr
  package:
    name: xorg-xrandr
    state: latest


- name: Install xorg-xsetroot
  package:
    name: xorg-xsetroot
    state: latest


- name: Install xautolock
  package:
    name: xautolock
    state: latest


- name: Configure .xinitrc
  copy:
    src: files/xorg/.xinitrc
    dest: ~/.xinitrc
  become: True
  become_user: "{{ user.name }}"


- name: Configure .Xresources
  copy:
    src: files/xorg/.Xresources
    dest: ~/.Xresources
  become: True
  become_user: "{{ user.name }}"


- name: Install xorg-xbacklight
  package:
    name: xorg-xbacklight
    state: latest


- name: Install xdg-user-dirs
  package:
    name: xdg-user-dirs
    state: latest


- name: Create home directory structure
  command: xdg-user-dirs-update
  become: True
  become_user: "{{ user.name }}"


- name: Create xdg Configuration Directory
  file:
    path: ~/.local/share/applications
    state: directory
    recurse: True
  become: True
  become_user: "{{ user.name }}"


- name: Configure xdg Default Applications
  copy:
    src: files/xorg/defaults.list
    dest: ~/.local/share/applications/defaults.list
  become: True
  become_user: "{{ user.name }}"


- name: Install xterm
  package:
    name: xterm
    state: latest
