#!/usr/bin/zsh


if [[ ${#} < 2 ]];
then
	echo "Usage: ${0} BRANCH MESSAGE"
	return -1
fi

local BRANCH=${1}
local MESSAGE=${2}

MASTER_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@refs/remotes/origin/@@')

if [[ ${?} -ne 0 ]];
then
	echo "Failed to determine master branch!"
	return -1
fi

echo ${BRANCH} ${MESSAGE}

git checkout ${BRANCH}

if [[ ${?} -ne 0 ]];
then
	echo "Failed to checkout: ${BRANCH}"
	return -1
fi

git reset $(git merge-base ${MASTER_BRANCH} ${BRANCH})

if [[ ${?} -ne 0 ]];
then
	echo "Failed to reset branch!"
	return -1
fi

git add -A

if [[ ${?} -ne 0 ]];
then
	echo "Failed to add all commits!"
	return -1
fi

git commit -m "${MESSAGE}"

if [[ ${?} -ne 0 ]];
then
	echo "Failed to commit changes!"
	return -1
fi

git push origin ${BRANCH} --force

if [[ ${?} -ne 0 ]];
then
	echo "Failed to push changes!"
	return -1
fi
