---
- name: Add spotify apt key
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    id: 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45


- name: Add spotify apt repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    update_cache: True


- name: Install spotify-client
  package:
    name: spotify-client
