---
- name: Install htop
  apt:
    name: htop
    state: latest
  become: True


- name: Install ranger
  apt:
    name: ranger
    state: latest
  become: True

- name: Install firefox
  apt:
    name: firefox
    state: latest
  become: True


- name: Install git
  apt:
    name: git
    state: latest
  become: True


- name: Configure git User Name
  git_config:
    name: user.name
    value: Patrick Murray
    scope: global


- name: Configure git User Email
  git_config:
    name: user.email
    value: patrickm129@gmail.com
    scope: global


- name: Install keepassxc
  apt:
    name: keepassxc
    state: latest
  become: True

