---
- name: Install htop
  apt:
    name: htop
    state: latest
  become: True


- name: Install ranger
  apt:
    name: ranger
    state: latest
  become: True

- name: Install firefox
  apt:
    name: firefox
    state: latest
  become: True

