---
- name: Install boto
  package:
    name: python-boto
    state: latest
  become: True

- name: Install boto3
  package:
    name: python-boto3
    state: latest
  become: True

- name: Create AWS configuration directory
  file:
    path: ~/.aws
    state: directory

- name: Configure AWS
  copy:
    src: files/config
    dest: ~/.aws/config

- name: Configure AWS credentials
  copy:
    src: files/credentials
    dest: ~/.aws/credentials
