---
roles:
  - common
  - network
  - window_manager
  - file_management
  - web_browser
  - development
  - system_administration
  - multimedia
  - documentation
  - security
  - graphic_design
  - finance
  - unixporn

network:
  ethernet_interface: enp0s25
  wireless_interface: wlp3s0

