---
roles:
  - common
#  - network
  - window_manager
  - file_management
  - web_browser
  - development
  - system_administration
  - multimedia
  - documentation
  - security
  - graphic_design
  - finance
  - unixporn

network:
  ethernet_interface: null
  wireless_interface: null

