---
- name: Add APT GPG Key
  apt_key:
    url: https://linux-packages.resilio.com/resilio-sync/key.asc
  become: True


- name: Add APT Repository
  apt_repository:
    repo: deb https://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
    state: present
  become: True


- name: Install Resilio-Sync
  apt:
    name: resilio-sync
    state: latest
  become: True


- name: Initialize Installation
  script: /etc/resilio-sync/init_user_config.sh


- name: Configure systemd Service
  copy:
    src: "files/resilio-sync.service"
    dest: "/lib/systemd/system/resilio-sync.service"
  become: True


- name: Reload systemd Service
  systemd:
    name: resilio-sync
    daemon_reload: True
  become: True


- name: Start systemd Service
  systemd:
    name: resilio-sync
    enabled: True
    state: started
  become: True

